### PR TITLE
Add cocoapods support

### PR DESCRIPTION
**Pull request by sodastsai**
I've written a simple podspec here. The new LICENSE file is used to meet the requirement of Cocoapods.

Here are some tasks to do to make this SDK fully support cocoapods integration:
1. Add a tag to each release version
2. Change the source configuration in podspec (Line 57)
3. Push to the Cocoapods Spec Repo (via ```pod``` command)

### CODE REVIEW

**Comment by sodastsai** [comment]
any responses?

**Comment by mikz** [comment]
I'm sorry, but I have no idea how cocoa pods work.
I have pods in my RubyMotion project. If you give me command how can I use it from a branch I'll be glad to try it out.

**Comment by sodastsai** [comment]
I haven't use RubyMotion before ...

When using Xcode to develop iOS app directly, I just
1) create a ```Podfile``` with standard content
2) add ```pod 'PhilipsHueSDK'```
3) then run ```pod install```, the sdk will be integrated into my project :)

btw, since it's still under testing, I haven't submitted this podspec to Cocoapods trunk, so the line ```pod 'PhilipsHueSDK'``` won't work. you have to change to ```pod 'PhilipsHueSDK', :podspec => 'https://raw.githubusercontent.com/sodastsai/PhilipsHueSDK-iOS-OSX/master/PhilipsHueSDK.podspec'```, since it's still hosted on my personal github account

**Comment by sodastsai** [comment]
any updates on this? or I'd rather to cancel this pull request :(

**Comment by mikz** [comment]
I tried it now and the spec works I guess. I was not able to build my project, because RubyMine switched to arm64 builds and build fails with: `ld: can't map file, errno=22 file '/Users/.../Developer/GoodNightHue/vendor/Pods/PhilipsHueSDK/HueSDK_iOS.framework' for architecture i386`
However, that is not an issue of this PR. 

One thing might be missing and that would be RELEASE.md instructions for Philips team to release new pods (tag, push tag, change podspec, ...).

Good job!

**Comment by williampower** [comment]
@mikz 
When you run "pod --version" in the terminal, what's your output? 
I might be missing it, but what's the connection with RubyMine? 
Once you've run "pod install", are you opening the workspace or the original project? (It should be the workspace once you've run "pod install")

Sorry for the slow reply, was off the internets for the last month. :smile:

**Comment by mikz** [comment]
@williampower sorry, I meant RubyMotion (the Ruby for iOS), not RubyMine (the IDE).
I have latest pod (`0.35.0`). But with RubyMotion, you don't use `Podfile`, but specify the dependencies in `Rakefile`. It is using [motion-cocoapods](https://github.com/HipByte/motion-cocoapods) and here is my [Podfile.lock](https://gist.github.com/mikz/6eabf98b01f34b83da50).

I'll try to rebuild everything from scratch. Can you confirm the SDK is also for 64bits ?

**Comment by sodastsai** [comment]
the content of ```Podfile.lock``` seems correct.

To check whether the binary is 64bit or not, you could use ```lipo``` command
Following is mine output:
```
sodas-macbook-pro:PhilipsHueSDK-iOS-OSX sodas$ lipo -info HueSDK_OSX.framework/HueSDK_OSX 
input file HueSDK_OSX.framework/HueSDK_OSX is not a fat file
Non-fat file: HueSDK_OSX.framework/HueSDK_OSX is architecture: x86_64
sodas-macbook-pro:PhilipsHueSDK-iOS-OSX sodas$ xcrun -sdk iphoneos lipo -info HueSDK_iOS.framework/HueSDK_iOS 
Architectures in the fat file: HueSDK_iOS.framework/HueSDK_iOS are: i386 x86_64 armv7 armv7s arm64 
```
It seems both iOS and OS X SDK support 64bits.

**Comment by mikz** [comment]
So I got it working. The error was because it was trying to link a folder instead of a library. The project was kind of outdated, so updating everything helped.

:star: :star2: :shipit: :star2: :star: 

Good job and thanks!

**Comment by mikz** [comment]
@williampower bump!

Would be awesome if this could be merged.

**Comment by williampower** [comment]
@pverh Can you help us get eyes on this?

**Comment by sodastsai** [comment]
after checked and merged, remember to [push to cocoapods's trunk repo](http://guides.cocoapods.org/making/getting-setup-with-trunk.html)

Thanks.

**Comment by mikz** [comment]
It is very pity, that this didn't go in :-1:

**Comment by sodastsai** [comment]
after waiting for long days, I think guys are not interesting in this so I closed it. :(
you could still use this SKD with Cocoapods by assigning custom podspec path
```
pod 'PhilipsHueSDK',
    :podspec => 'https://raw.githubusercontent.com/sodastsai/PhilipsHueSDK-iOS-OSX/master/PhilipsHueSDK.podspec',
```

**Comment by tumtumtum** [comment]
Thanks for your hard work!

**Pull request closed without merging**
